import type { Metadata } from "next";
import {  Quicksand } from "next/font/google";
import "./globals.scss";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Emibbuns",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
				<div className="bg-sky"></div>
				<img src="/backgrounds/forestry.png" className="bg_mt" alt="" />
				{/* <img src="/backgrounds/forestry.png" className="bg_sky" alt="" /> */}
				{children}
			</body>
    </html>
  );
}
